#!/bin/bash
#
# Fetch a library, build it twice, and generate its drivers.
#
#   build-lib.sh <gsl|gmp>
#
# Twice, because the two builds answer different questions:
#
#   <lib>-bc    LLVM bitcode, via wllvm and the same clang KLEE was built
#               against. This is what KLEE symbolically executes.
#   <lib>-cov   native, with clang's source-based coverage instrumentation.
#               This is what the generated tests are replayed against, and
#               where the coverage number comes from.
#
# Both come from the same release tarball, so the source lines the coverage
# step reports are the lines KLEE executed. Their config.h files are compared
# afterwards for the same reason: a feature probe that answers differently in
# the two builds means they are not the same program.
#
set -euo pipefail

LIB=${1:?usage: build-lib.sh <gsl|gmp>}
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
WORK=${FP_BENCH_WORK:-/mnt/baranem/fp_bench-work}

# The LLVM that KLEE was built against, and KLEE itself.
LLVM_PREFIX=${LLVM_PREFIX:-/mnt/baranem/llvm16/install}
KLEE_SRC=${KLEE_SRC:-/mnt/baranem/klee-float/3.2}
KLEE_BUILD=${KLEE_BUILD:-/mnt/baranem/klee-float/3.2-buildtest}
SHIM=${SHIM:-/mnt/baranem/klee-float/3.2-deps/shim-bin16}
PYENV=${PYENV:-/mnt/baranem/klee-float/deps/pyenv}

# The coverage build needs a clang carrying compiler-rt's profile runtime; the
# LLVM built for KLEE has none. It only has to agree with llvm-cov.
NATIVE_CC=${NATIVE_CC:-/usr/bin/clang}
JOBS=${JOBS:-$(nproc)}

# GSL and GMP come from ftp.gnu.org as verified tarballs. The rest are cloned:
# their releases live on github.com, which this network reaches over git but
# not over plain HTTP.
case $LIB in
  gsl) VER=2.8;   URL=https://ftp.gnu.org/gnu/gsl/gsl-2.8.tar.gz
       SHA=6a99eeed15632c6354895b1dd542ed5a855c0f15d9ad1326c6fe2b2c9e423190
       TAR=gsl-2.8.tar.gz; SRC=gsl-2.8
       # GSL's own configure picks -O2; nothing else is needed.
       CONFIGURE_EXTRA=()
       ARCHIVES=(.libs/libgsl.a cblas/.libs/libgslcblas.a) ;;
  fftw) VER=3.3.10; URL=https://www.fftw.org/fftw-3.3.10.tar.gz
       SHA=56c932549852cddcfafdab3820b0200c7742675be92179e59e6215b340e26467
       TAR=fftw-3.3.10.tar.gz; SRC=fftw-3.3.10
       # The codelets FFTW's planner dispatches to are generated by its own
       # OCaml generator at release time and ship only in the tarball; a git
       # checkout stops at "No rule to make target 'n1_2.c'".
       CONFIGURE_EXTRA=(--disable-fortran)
       ARCHIVES=(.libs/libfftw3.a)
       # fftw3.h lives under api/ in the source tree rather than at the root.
       INCSUB=api ;;
  gmp) VER=6.3.0; URL=https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
       SHA=a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898
       TAR=gmp-6.3.0.tar.xz; SRC=gmp-6.3.0
       # GMP's mpn layer ships as hand-written assembly per architecture and
       # KLEE cannot execute it, so both builds take the C path. This is the
       # single largest caveat on any GMP number here: what is measured is
       # GMP's C fallback, not the code that ships.
       CONFIGURE_EXTRA=(--disable-assembly)
       # Only the whole library. GMP also builds a convenience archive per
       # directory, all of which libgmp.a already contains, and linking those
       # too defines every symbol twice.
       ARCHIVES=(.libs/libgmp.a) ;;
  openlibm) VER=v0.8.7; REPO=https://github.com/JuliaMath/openlibm; TAG=v0.8.7 ;;
  cxsparse) VER=git; REPO=https://github.com/DrTimothyAldenDavis/SuiteSparse
       # SuiteSparse ships GraphBLAS, LAGraph, ParU and a dozen more; a full
       # clone is most of a gigabyte to reach two directories. CXSparse needs
       # only itself and SuiteSparse_config.
       SPARSE="CXSparse SuiteSparse_config" ;;
  sundials) VER=git; REPO=https://github.com/LLNL/sundials ;;
  blis) VER=git; REPO=https://github.com/flame/blis
       # 'generic' is BLIS's assembly-free configuration, for the same reason
       # GMP takes --disable-assembly: KLEE cannot execute the tuned kernels,
       # and every other configuration selects some.
       BLIS_CONFIG=generic ;;
  *) echo "unknown library: $LIB" >&2; exit 2 ;;
esac


export PATH="$PYENV/bin:$SHIM:$LLVM_PREFIX/bin:$PATH"
export LLVM_COMPILER=clang
export LLVM_COMPILER_PATH="$SHIM"
export LLVM_CC_NAME=klee-clang
export LLVM_CXX_NAME=klee-clang++

mkdir -p "$WORK"
cd "$WORK"

[ -x "$PYENV/bin/wllvm" ] || "$PYENV/bin/pip" -q install wllvm

# ---------------------------------------------------------------------------
# Libraries with their own build system, cloned rather than downloaded.
# ---------------------------------------------------------------------------
if [ "${REPO:-}" != "" ]; then
  if [ ! -d "$WORK/$LIB-src" ]; then
    if [ -n "${SPARSE:-}" ]; then
      git clone -q --depth 1 --filter=blob:none --sparse "$REPO" "$WORK/$LIB-src"
      ( cd "$WORK/$LIB-src" && git sparse-checkout set $SPARSE )
    else
      git clone -q --depth 1 ${TAG:+--branch "$TAG"} "$REPO" "$WORK/$LIB-src"
    fi
  fi

  # Each of these has its own build system, and each needs to run it before a
  # header exists to generate from: bli_config.h and sundials_config.h are
  # produced by the configure step, and clang emits a *partial* AST before
  # failing on a missing one -- so a generator run against an unconfigured tree
  # silently sees a fraction of the API and reports a number that looks fine.
  build_cmake() {  # <destination> <cc> <cflags>
    local dest=$1 cc=$2 cflags=$3
    rm -rf "$dest"
    cp -a "$WORK/$LIB-src" "$dest"
    cmake -S "$dest" -B "$dest/build" \
      -DCMAKE_C_COMPILER="$cc" -DCMAKE_C_FLAGS="$cflags" \
      -DCMAKE_INSTALL_PREFIX="$dest/inst" \
      -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON \
      -DEXAMPLES_ENABLE_C=OFF -DBUILD_TESTING=OFF \
      -DBUILD_FORTRAN_MODULE_INTERFACE=OFF > "$dest/config.log" 2>&1
    cmake --build "$dest/build" -j"$JOBS" > "$dest/build.log" 2>&1
    cmake --install "$dest/build" > "$dest/install.log" 2>&1
  }

  build_autoconf() {  # <destination> <cc> <cflags>
    local dest=$1 cc=$2 cflags=$3
    rm -rf "$dest"
    cp -a "$WORK/$LIB-src" "$dest"
    ( cd "$dest"
      [ -f configure ] || sh bootstrap.sh --disable-fortran > boot.log 2>&1 || true
      CC="$cc" CFLAGS="$cflags" ./configure --disable-shared --enable-static \
        --disable-fortran --prefix="$dest/inst" > config.log 2>&1
      make -j"$JOBS" > build.log 2>&1
      make install > install.log 2>&1 )
  }

  build_cxsparse() {  # <destination> <cc> <cflags>
    local dest=$1 cc=$2 cflags=$3
    rm -rf "$dest"
    cp -a "$WORK/$LIB-src" "$dest"
    # The top-level CMakeLists selects subprojects, and CXSparse alone would
    # go looking for a SuiteSparse_config it has to be told to build first.
    #
    # OpenMP off: SuiteSparse_config times itself with omp_get_wtime, which is
    # an undefined reference at link time without -fopenmp, and a runtime KLEE
    # could not call with it. Nothing in the numerics calls it.
    cmake -S "$dest" -B "$dest/build" \
      -DSUITESPARSE_ENABLE_PROJECTS=cxsparse \
      -DSUITESPARSE_USE_OPENMP=OFF -DSUITESPARSE_CONFIG_USE_OPENMP=OFF \
      -DCMAKE_C_COMPILER="$cc" -DCMAKE_C_FLAGS="$cflags" \
      -DCMAKE_INSTALL_PREFIX="$dest/inst" \
      -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON \
      -DSUITESPARSE_DEMOS=OFF -DBUILD_TESTING=OFF > "$dest/config.log" 2>&1
    cmake --build "$dest/build" -j"$JOBS" > "$dest/build.log" 2>&1
    cmake --install "$dest/build" > "$dest/install.log" 2>&1
  }

  build_openlibm() {  # <destination> <cc> <cflags>
    local dest=$1 cc=$2 cflags=$3
    rm -rf "$dest"
    cp -a "$WORK/$LIB-src" "$dest"
    ( cd "$dest"
      # amd64_SRCS is the arch's source list, and on x86-64 it is 23 assembly
      # files that KLEE cannot execute. Overriding it to fenv.c alone leaves
      # the arch's floating-point environment correct while every one of those
      # 23 falls back to the C in src/ -- the same trade GMP makes with
      # --disable-assembly, and the same caveat applies: what is measured is
      # the C path. ARCH stays amd64 rather than borrowing a pure-C
      # architecture's directory, because that directory's fenv.c is written
      # for a different machine.
      # CFLAGS rather than CFLAGS_add: OpenLibm appends its own essentials to
      # CFLAGS_add (-fno-builtin above all, without which clang is free to
      # turn a call to sin into the intrinsic it is implementing), and a
      # command-line assignment would discard them. CFLAGS is the hook it
      # leaves free, and it suppresses OpenLibm's own -O3 when it carries a -O.
      make -j"$JOBS" ARCH=amd64 amd64_SRCS=fenv.c \
        CC="$cc" USEGCC=0 USECLANG=1 CFLAGS="$cflags" \
        prefix="$dest/inst" > build.log 2>&1
      make ARCH=amd64 amd64_SRCS=fenv.c prefix="$dest/inst" \
        install-static install-headers > install.log 2>&1 )
  }

  build_blis() {  # <destination> <cc> <cflags>
    local dest=$1 cc=$2 cflags=$3
    rm -rf "$dest"
    cp -a "$WORK/$LIB-src" "$dest"
    ( cd "$dest"
      # --disable-tls, because KLEE cannot execute llvm.threadlocal.address
      # and BLIS reads a thread-local error-checking level from inside
      # bli_init_once. Every BLIS driver died there, on its first call into
      # the library, before this. BLIS calls disabling TLS dangerous and it is
      # -- for a program with threads in it, which a KLEE driver is not.
      CC="$cc" CFLAGS="$cflags" ./configure --disable-shared --enable-static \
        --disable-threading --disable-tls \
        --prefix="$dest/inst" "$BLIS_CONFIG" > config.log 2>&1
      # BLIS compiles its reference kernels on its own terms, appending -O3,
      # -funsafe-math-optimizations, -ffp-contract=fast and -fopenmp-simd
      # *after* whatever CFLAGS it was given -- so -fno-vectorize in CFLAGS is
      # simply overruled, and the inner loop of every gemm came out as
      # llvm.vector.reduce.fadd, which KLEE cannot execute.
      #
      # These four variables are where those flags live, and make lets them be
      # replaced. Unsafe math and contraction would have to go regardless of
      # KLEE: they let the compiler reassociate sums and fuse a multiply-add
      # into one rounding, so the bitcode would no longer compute what the
      # source says, in a benchmark whose whole subject is what the source
      # says. Both builds get it, so that a replayed test computes what KLEE
      # explored.
      make -j"$JOBS" COMPSIMDFLAGS= \
        CROPTFLAGS=-O2 CKOPTFLAGS=-O2 \
        CRVECFLAGS="-fno-vectorize -fno-slp-vectorize -ffp-contract=off" \
        CKVECFLAGS="-fno-vectorize -fno-slp-vectorize -ffp-contract=off" \
        > build.log 2>&1
      make install > install.log 2>&1 )
  }

  # A library that ships more than one archive needs all of the ones a driver
  # calls into. SUNDIALS keeps its context and its error handling in
  # libsundials_core, apart from the vectors in libsundials_nvecserial, and
  # taking only the latter left SUNContext_Create outside the module: every
  # SUNDIALS driver died on it as a failed external call, thirty instructions
  # in, having never entered the library. The native link line had both from
  # the start, which is why nothing looked wrong until one was run.
  case $LIB in
    blis)     BUILD=build_blis;     ARCS=(libblis.a);     HDR=blis.h ;;
    openlibm) BUILD=build_openlibm; ARCS=(libopenlibm.a); HDR=openlibm_math.h ;;
    cxsparse) BUILD=build_cxsparse; ARCS=(libcxsparse.a libsuitesparseconfig.a)
              HDR=cs.h ;;
    sundials) BUILD=build_cmake;    ARCS=(libsundials_nvecserial.a
                                          libsundials_sunmatrixdense.a
                                          libsundials_sunlinsoldense.a
                                          libsundials_core.a)
              HDR=sundials/sundials_config.h ;;
    fftw)     BUILD=build_autoconf; ARCS=(libfftw3.a);    HDR=fftw3.h ;;
  esac

  if [ ! -f "$WORK/$LIB.bc" ]; then
    # -fno-openmp-simd is the one that is not obvious. BLIS's reference
    # kernels carry a PRAGMA_SIMD, which expands to #pragma omp simd, and
    # clang honours that even under -fno-vectorize: the inner loop of every
    # gemm came out as llvm.vector.reduce.fadd.v2f64, which KLEE cannot
    # execute. Scalar is also the right shape for this benchmark -- a
    # horizontal reduction is a different summation order, so a different
    # rounding, from the one the source describes.
    "$BUILD" "$WORK/$LIB-bc" wllvm \
      "-O2 -g -fno-vectorize -fno-slp-vectorize -fno-openmp-simd \
       -Wno-implicit-function-declaration"
    parts=()
    for arc in "${ARCS[@]}"; do
      # -print -quit rather than a pipe into head: under `set -o pipefail`,
      # head closing the pipe kills find with SIGPIPE, the pipeline reports
      # failure, and `set -e` takes the whole script down at the assignment.
      a=$(find "$WORK/$LIB-bc/inst" "$WORK/$LIB-bc/build" \
            -name "$arc" -print -quit 2>/dev/null)
      [ -n "$a" ] || { echo "no $arc built for $LIB" >&2; exit 1; }
      extract-bc -b "$a" -o "$WORK/$LIB.$arc.bc"
      parts+=("$WORK/$LIB.$arc.bc")
    done
    "$LLVM_PREFIX/bin/llvm-link" "${parts[@]}" -o "$WORK/$LIB.bc"
    rm -f "${parts[@]}"
  fi
  if [ ! -d "$WORK/$LIB-cov/inst" ]; then
    "$BUILD" "$WORK/$LIB-cov" "$NATIVE_CC" \
      "-O0 -g -fprofile-instr-generate -fcoverage-mapping -fno-openmp-simd \
       -Wno-implicit-function-declaration"
  fi

  # The generated monolithic header, which is what the generator reads and what
  # the drivers include.
  INC=$(find "$WORK/$LIB-bc/inst" "$WORK/$LIB-bc/build" -name "$(basename "$HDR")" \
          -printf '%h\n' -quit 2>/dev/null)
  # A header nested under a directory of its own (sundials/...) is included as
  # such, so the include path is the directory above it.
  case $HDR in */*) INC=$(dirname "$INC") ;; esac
  rm -rf "$ROOT/$LIB/drivers"; mkdir -p "$ROOT/$LIB/drivers"
  "$HERE/gen-drivers.py" --library "$LIB" --include "$INC" --out "$ROOT/$LIB/drivers"
  echo
  echo "$LIB $VER${BLIS_CONFIG:+ ($BLIS_CONFIG)}"
  echo "  bitcode:  $WORK/$LIB.bc"
  echo "  header:   $INC/$HDR"
  echo "  drivers:  $(ls "$ROOT/$LIB/drivers"/*.c 2>/dev/null | wc -l)"
  exit 0
fi

###############################################################################
# 1. Fetch, and say what was fetched
###############################################################################
[ -f "$TAR" ] || curl -sSL -o "$TAR" "$URL"
echo "$SHA  $TAR" | sha256sum -c -

###############################################################################
# 2. Bitcode -- what KLEE executes
###############################################################################
if [ ! -f "$WORK/$LIB.bc" ]; then
  rm -rf "$LIB-bc"
  tar xf "$TAR" && mv "$SRC" "$LIB-bc"
  ( cd "$LIB-bc"
    # -fno-vectorize keeps the bitcode scalar, so what KLEE executes lines up
    # with the -O0 coverage build. -Wno-implicit-* is not cosmetic: a current
    # clang makes implicit declarations an error, several configure probes call
    # exit() without stdlib.h, and a probe that fails to compile is recorded as
    # a failed feature -- giving the two builds different config.h files.
    CC=wllvm \
    CFLAGS="-O2 -g -fno-vectorize -fno-slp-vectorize -Wno-implicit-function-declaration -Wno-implicit-int" \
      ./configure --disable-shared --enable-static "${CONFIGURE_EXTRA[@]}" \
      > config.log 2>&1
    make -j"$JOBS" > build.log 2>&1 )
  # extract-bc names archive members by basename, and both libraries have
  # same-named objects in different directories, so the archive form silently
  # loses all but one. Take the whole-module form; the per-driver prune below
  # cuts it back down.
  bcs=()
  for a in "${ARCHIVES[@]}"; do
    extract-bc -b "$WORK/$LIB-bc/$a" -o "$WORK/$LIB-bc/$a.bc"
    bcs+=("$WORK/$LIB-bc/$a.bc")
  done
  llvm-link "${bcs[@]}" -o "$WORK/$LIB.bc"
fi

###############################################################################
# 3. Native, instrumented -- what the tests are replayed against
###############################################################################
if [ ! -d "$WORK/$LIB-cov/.libs" ]; then
  rm -rf "$LIB-cov"
  tar xf "$TAR" && mv "$SRC" "$LIB-cov"
  ( cd "$LIB-cov"
    CC="$NATIVE_CC" \
    CFLAGS="-O0 -g -fprofile-instr-generate -fcoverage-mapping -Wno-implicit-function-declaration -Wno-implicit-int" \
    LDFLAGS="-fprofile-instr-generate" \
      ./configure --disable-shared --enable-static "${CONFIGURE_EXTRA[@]}" \
      > config.log 2>&1
    make -j"$JOBS" > build.log 2>&1 )
fi

# The two trees must agree on what they compiled, or the coverage step reports
# on source KLEE never saw.
cfg_of() { grep -v -e '^/\*' -e '_CC "' -e 'COMPILER' "$1" 2>/dev/null; }
if ! diff -q <(cfg_of "$WORK/$LIB-bc/config.h") \
             <(cfg_of "$WORK/$LIB-cov/config.h") > /dev/null 2>&1; then
  echo "WARNING: the two $LIB builds configured differently:" >&2
  diff <(cfg_of "$WORK/$LIB-bc/config.h") <(cfg_of "$WORK/$LIB-cov/config.h") >&2 || true
fi

###############################################################################
# 4. Drivers, from the header of the build that was just made
###############################################################################
INC=$WORK/$LIB-bc${INCSUB:+/$INCSUB}
rm -rf "$ROOT/$LIB/drivers"
mkdir -p "$ROOT/$LIB/drivers"
"$HERE/gen-drivers.py" --library "$LIB" --include "$INC" \
                       --out "$ROOT/$LIB/drivers"

echo
echo "$LIB $VER"
echo "  bitcode:   $WORK/$LIB.bc"
echo "  coverage:  $WORK/$LIB-cov"
echo "  drivers:   $(ls "$ROOT/$LIB/drivers"/*.c 2>/dev/null | wc -l)"
echo "  skipped:   $ROOT/$LIB/skipped.tsv"
