#!/bin/bash
#
# Build GCC's libquadmath to LLVM bitcode with clang, so that binary128 math
# can be symbolically executed rather than called out to.
#
#   build-libquadmath.sh
#   QM_SRC=/usr/src/debug/gcc-10.5.0/libquadmath build-libquadmath.sh
#
# Link the result into a program that uses the #define sin sinq block:
#
#   llvm-link -o prog_linked.bc prog.bc libquadmath-math.bc
#   klee --link-llvm-lib=<uclibc>/lib/libm.a prog_linked.bc
#
# libquadmath ships as part of GCC and has no standalone build, so this
# compiles its sources directly and llvm-links them. Two things GCC's own
# build would have supplied are generated below rather than searched for,
# which is what makes the script self-contained:
#
#   config.h   configure generates it. Only the HAVE_* macros the sources
#              actually test are needed -- see
#              `grep -rhoE 'HAVE_[A-Z0-9_]+' "$QM_SRC"`.
#
#   shim.h     clang has no __builtin_huge_valq. __builtin_inff128 is the
#              same value. Without this the ten complex functions do not
#              compile and everything else does, which is a quiet way to end
#              up with a partial library.
#
# ---------------------------------------------------------------------------
# What this deliberately does not build, and why it is math/ only
#
# printf/ and strtod/ are the string conversion layer. Three things stop them:
#
#   * printf/printf_fp.c uses GCC nested functions, which clang cannot compile
#     at all. quadmath_snprintf therefore has no body.
#
#   * strtod/strtoflt128.c needs grouping.h, which the GCC debuginfo source
#     package does not ship. This is what `#define atof strtoflt128` needs, so
#     string-to-quad parsing is not available.
#
#   * Both reference __clz_tab, a libgcc table. Linking them into a KLEE
#     module fails before execution starts with
#         KLEE: ERROR: Unable to load symbol(__clz_tab) while initializing globals
#     so including them costs the whole run rather than just those functions.
#
# They also need GCC's own include/longlong.h, which the debuginfo package
# does not ship either. GMP's copy of the same name is not a substitute:
# libquadmath's gmp-impl.h expects GCC's variant, with ASSERT, LIKELY and
# __clz_tab. math/ needs none of that, which is the other reason to stop here.
#
# The macro block that motivates all of this -- sin/cos/tan/exp/log/pow/sqrt/
# ceil/fabs/floor/fmod/modf and the inverse and hyperbolic functions -- is
# served entirely by math/. atof is the one entry point that is not.
set -eu

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
QM_SRC=${QM_SRC:-/usr/src/debug/gcc-10.5.0+git3415/libquadmath}
LLVM_PREFIX=${LLVM_PREFIX:-/mnt/baranem/llvm16/install}
OUT=${OUT:-${FP_BENCH_WORK:-/mnt/baranem/fp_bench-work}/libquadmath}

[ -d "$QM_SRC/math" ] || {
  echo "no libquadmath sources at $QM_SRC" >&2
  echo "Point QM_SRC at a GCC source tree's libquadmath/ directory; on a" >&2
  echo "distribution that ships one, the gcc debuginfo source package has it." >&2
  exit 1; }

mkdir -p "$OUT/bc"
cd "$OUT"

cat > config.h <<'CONFIG'
/* Generated by common/build-libquadmath.sh: a stand-in for the config.h that
   libquadmath's configure would emit. Only the macros the sources test are
   here. HAVE_PRINTF_HOOKS is deliberately left undefined -- it pulls in
   glibc's register_printf_specifier, which is not something to symbolically
   execute. */
#define HAVE_ERRNO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_CTYPE_H 1
#define HAVE_LOCALE_H 1
#define HAVE_WCHAR_H 1
#define HAVE_WCTYPE_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_FENV_H 1
#define HAVE_FESETROUND 1
#define HAVE_FETESTEXCEPT 1
#define HAVE_FEHOLDEXCEPT 1
#define HAVE_FESETENV 1
#define HAVE_FEUPDATEENV 1
#define HAVE_STRTOULL 1
#define HAVE_SQRTL 1
#define HAVE_MATH_H_SIGNGAM 1
#define HAVE_HIDDEN_VISIBILITY 1
CONFIG

cat > shim.h <<'SHIM'
/* Generated by common/build-libquadmath.sh. clang has no
   __builtin_huge_valq; __builtin_inff128 is the same value. Applied with
   -include so it reaches every translation unit. */
#ifdef __clang__
#define __builtin_huge_valq() __builtin_inff128()
#endif
SHIM

ok=0 failed=0
: > build-errors.txt
for src in "$QM_SRC"/math/*.c; do
  obj="bc/math_$(basename "$src" .c).bc"
  if "$LLVM_PREFIX/bin/clang" -emit-llvm -c -g -O1 -std=gnu11 -fno-builtin \
       -include shim.h -I. -I"$QM_SRC" -I"$QM_SRC/math" \
       -o "$obj" "$src" 2>>build-errors.txt
  then ok=$((ok + 1))
  else failed=$((failed + 1)); echo "FAILED $src" >> build-errors.txt; fi
done
echo "math/: $ok compiled, $failed failed"

[ "$failed" -eq 0 ] || {
  echo "REFUSING: a partial libquadmath links and runs, and only shows up as" >&2
  echo "an undefined reference for whichever function the program happens to" >&2
  echo "call. See $OUT/build-errors.txt" >&2
  exit 1; }

"$LLVM_PREFIX/bin/llvm-link" -o libquadmath-math.bc bc/math_*.bc
echo "wrote $OUT/libquadmath-math.bc"

# Say plainly which of the macro block's entry points made it, so a missing
# one is noticed here rather than as an undefined reference mid-run.
"$LLVM_PREFIX/bin/llvm-nm" --defined-only libquadmath-math.bc > symbols.txt 2>/dev/null
missing=0
for fn in sinq cosq tanq asinq acosq atanq sinhq coshq tanhq asinhq acoshq \
          atanhq expq logq powq sqrtq ceilq fabsq floorq fmodq modfq; do
  awk -v s="$fn" '$3 == s && $2 ~ /[TtDdWwB]/ { found = 1 }
                  END { exit !found }' symbols.txt || {
    echo "  MISSING $fn"; missing=$((missing + 1)); }
done
if [ "$missing" -eq 0 ]; then
  echo "  all 21 math entry points of the macro block are defined"
else
  echo "  $missing entry points missing -- see $OUT/build-errors.txt" >&2
  exit 1
fi
echo "  atof/strtoflt128 is NOT available; see the header of this script"
