#!/usr/bin/env python3
"""Write a header for f2cblaslapack, which ships none.

    f2c-protos.py <precision-letter> <out.h> <source-dir>...

PETSc's f2cblaslapack is f2c output: 3,851 translation units, each holding one
routine, and not a single prototype anywhere. PETSc declares what it calls in
its own headers, so the library never needed one. The generator reads a header
through clang's AST, so this makes the one the library is missing -- from the
definitions themselves, which keeps it honest: a signature here is a signature
the library actually has, not one somebody transcribed.

f2c writes every definition the same way, `<rettype> <name>_(params)` followed
by a brace, with the parameter list wrapped across lines at whatever column it
reached. Take from the return type to the parenthesis that closes the list.
"""
import os
import re
import sys

RET = r"(?:void|int|integer|quadreal|doublereal|real|halfreal|logical)"


def prototype(path, name):
    """The definition of `name` in `path`, as a prototype, or None."""
    src = open(path, errors="ignore").read()
    m = re.search(r"^[ \t]*(?:extern[ \t]+)?%s[ \t]+(%s_)[ \t]*\("
                  % (RET, re.escape(name)), src, re.M)
    if not m:
        return None
    depth, i = 0, m.end() - 1
    while i < len(src):
        if src[i] == "(":
            depth += 1
        elif src[i] == ")":
            depth -= 1
            if depth == 0:
                return re.sub(r"\s+", " ", src[m.start():i + 1]).strip() + ";"
        i += 1
    return None


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    letter, out, dirs = sys.argv[1], sys.argv[2], sys.argv[3:]

    protos, seen = [], set()
    for d in dirs:
        for f in sorted(os.listdir(d)):
            if not f.endswith(".c"):
                continue
            name = f[:-2]
            # One precision at a time. The routines are named by their leading
            # letter -- q for __float128, d for double -- except for the
            # integer-returning i?amax, whose precision is the *second* letter.
            if not (name.startswith(letter) or
                    (name.startswith("i") and name[1:2] == letter)):
                continue
            p = prototype(os.path.join(d, f), name)
            if p and name not in seen:
                seen.add(name)
                protos.append(p)

    with open(out, "w") as fh:
        fh.write("/* Generated by common/f2c-protos.py -- do not edit. */\n\n")
        # f2c.h types the whole library from this macro, and it has to come
        # first. Only `real` and `doublereal` exist unconditionally; quadreal
        # and halfreal are inside their own branch, so a header emitted without
        # the macro declares functions in a type that does not exist -- and
        # clang answers a missing type with a *partial* AST rather than
        # nothing, so the generator would emit drivers that cannot compile.
        macro = {"q": "__LAPACK_PRECISION_QUAD", "h": "__LAPACK_PRECISION_HALF",
                 "s": "__LAPACK_PRECISION_SINGLE"}.get(letter)
        if macro:
            fh.write("#define %s\n" % macro)
        fh.write('#include "f2c.h"\n\n')
        for p in protos:
            fh.write(p + "\n")
    print("%s: %d prototypes -> %s" % (letter, len(protos), out))


if __name__ == "__main__":
    main()
